# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build on Linux and Windows 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Clean Project LeetCode
      run: dotnet clean LeetCode
      #- name: Clean Project LeetCode
      #run: dotnet clean LeetCode.Test
    - name: Restore dependencies
      run: dotnet restore LeetCode
    - name: Restore dependencies
      run: dotnet restore LeetCode.Test
    - name: Build
      run: dotnet build LeetCode --no-restore
    - name: Build
      run: dotnet build LeetCode.Test --no-restore
    - name: Test
      run: dotnet test LeetCode.Test --no-build --verbosity normal
